### PR TITLE
feat(v1.0.8): updated SendMoney request, fixed safeTerminateWs

### LINKED ISSUE #65: clientApp.sendMoney<CBAppSendMoneyRequest> missing props
`https://docs.cdp.coinbase.com/coinbase-app/docs/api-transactions#send-money`

I have started to use your package, and it's amazing!
But it seems that the sendMoney function has fallen behind the CoinBase changes they've made? 

I manually added props such as `network?: string` and `is_self?: string` to `CBAppSendMoneyRequest` in my local `coinbase-app-client.d.ts` to move forward, but I thought I'd report it. 
Even though I've added more props to try and make it work, I have not been successful yet, neither with a direct node fetch.
I am in touch with CoinBase about that

Keep up the amazing work!

### PR DESCRIPTION
**Pull request by JJ-Cro**
fixes #65

- added safeTerminateWs 
- updated SendMoney reqeust to include travel rule
- updated order config to include vwap for submitOrder()

### CODE REVIEW

File: src/lib/BaseWSClient.ts [hunk 1]
```diff
@@ -340,7 +341,7 @@ export abstract class BaseWebsocketClient<
     const ws = this.getWs(wsKey);
     ws?.close();
     if (force) {
-      ws?.terminate();
+      safeTerminateWs(ws, true);
```
Comment (tiagosiebler) [inline src/lib/BaseWSClient.ts:344]:
```suggestion
      safeTerminateWs(ws);
```

File: src/lib/BaseWSClient.ts [hunk 2]
```diff
@@ -530,7 +531,7 @@ export abstract class BaseWebsocketClient<
 
       this.clearPongTimer(wsKey);
 
-      this.getWs(wsKey)?.terminate();
+      safeTerminateWs(this.getWs(wsKey));
```
Comment (tiagosiebler) [inline src/lib/BaseWSClient.ts:534]:
```suggestion
      safeTerminateWs(this.getWs(wsKey), true);
```

This is the _only_ call to close it, so here we do need to fallback to "close" if terminate is not available, or we have no way of closing this socket.

**Review by tiagosiebler — APPROVED** [review]
LGTM, thanks for the PR!
